#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  6 14:14:17 2022

@author: rushikeshnaik
"""
import time
class LogTime:
    
    def __init__(self,func):
        self.function = func
    
    def __call__(self,*args):
        print("Start time:",time.time())
        self.function(*args)
        print("End time:",time.time())

@LogTime
def sumNums(a,b,c):
    print(a+b+c)

def main():
    sumNums(10,1,1)
    
if __name__=="__main__":
    main()

        